### PR TITLE
Show tx signer

### LINKED ISSUE #116: Show transaction signer account
It depends on vocdoni node https://github.com/vocdoni/vocdoni-node/issues/1370

### PR DESCRIPTION
**Pull request by selankon**
Fix #116

image

### CODE REVIEW

**Review by emmdim — APPROVED** [review]
LGTM

**Comment by elboletaire** [comment]
But... the signer is not the account, is it? I don't see how useful is this, since copying a signer does not allow to search an account by such address (?)

**Comment by emmdim** [comment]
> But... the signer is not the account, is it? I don't see how useful is this, since copying a signer does not allow to search an account by such address (?)

At least in the raw of the vocdoni-node  the name used for the account is signer.
Example:
https://dev.explorer.vote/transactions/660284/0/1

Is that what you mean?

**Comment by elboletaire** [comment]
> > But... the signer is not the account, is it? I don't see how useful is this, since copying a signer does not allow to search an account by such address (?)
> 
> At least in the raw of the vocdoni-node the name used for the account is signer. Example: [dev.explorer.vote/transactions/660284/0/1](https://dev.explorer.vote/transactions/660284/0/1)
> 
> Is that what you mean?

What I mean is... what is that signer useful for if it's not the actual account?
imatge

**Review by elboletaire — APPROVED** [review]

**Comment by elboletaire** [comment]
I approved the changes, but my confusion with the signer comes due to the `create_account` transactions, where the signer is the account of the wallet who created such account.

But in these transactions, an `account` field is added, which shows the account recently created. May be a good idea to show it somehow, although may be done in a different PR (as you wish @selankon).

**Review by elboletaire — CHANGES_REQUESTED** [review]
~~I've changed my mind. You're pointing to a PR which added a new field `account`, but you're using a field named `signer`. You should do a ternary operation, and show the `account` by default, or the signer in case there's no account.~~

Never mind that last thought... I got really confused due to the vocdoni-node PR related to this one and different naming issues.

The only required change in this PR is not naming it `signer`, since they'll be always existing accounts and naming it `signer` adds confusion (since we now can name them `accounts`, `organizations` and adding `signer` would complicate things for end-users [as it did to me today, damn dyslexics]).

**Comment by selankon** [comment]
> The only required change in this PR is not naming it `signer`, since they'll be always existing accounts and naming it `signer` adds confusion (since we now can name them `accounts`, `organizations` and adding `signer` would complicate things for end-users [as it did to me today, damn dyslexics]).

So which name should I use? Account?

**Comment by elboletaire** [comment]
> So which name should I use? Account?

Yeah, @emmdim agreed

**Review by elboletaire — APPROVED** [review]

**Pull request merged**
