### PR TITLE
Add focuslock

### PR DESCRIPTION
**Pull request by elboletaire**
Also trying to execute the callback on enter key, but for unknown reason it's not working :\

### CODE REVIEW

**Comment by selankon** [comment]
Add a fix to make it working. 

First of all the input Enter event doesn't need to be debounced (have to be immediate). On the other hand the problem was that the PopoverCallback was not passed down to the Input, is because that it didn't work.

By the way, I consider that the `InputSearch` doesn't need to implement the `Enter` event because the callback is supposed to be called `onChange` and after the debounce time. So the Enter key won't be pressed any time. Also this input could be used inside a form without the debounce time, and pressing enter could execute the "form submit".

So, the Enter callback is a particular  feature only for the Popover (which has a "submit button" and the user may want to execute the search on "Enter"). I did the implementation here f1fb374

**Comment by selankon** [comment]
Another question is if the popover have to be closed after Enter pressed

**Comment by elboletaire** [comment]
> Another question is if the popover have to be closed after Enter pressed

The behavior of the input pressing the enter key should be like in any normal form, sending the form.

**Comment by selankon** [comment]
With this e218388 should be enough

**Pull request merged**
